import org.jetbrains.compose.compose
import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    kotlin("jvm") version "1.5.10"
    id("org.jetbrains.compose") version "0.4.0"
    id("org.jetbrains.dokka") version "1.4.32"
}

val ENV = System.getenv()


repositories {
    mavenLocal()
    maven {
        url = uri("https://gitlab.cri.epita.fr/api/v4/groups/3042/-/packages/maven/")
        credentials(HttpHeaderCredentials::class) {
            name = "Private-Token"
            value = ENV["ACCESS_TOKEN"]
        }
        authentication {
            create<HttpHeaderAuthentication>("header")
        }
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    mavenCentral()
    maven { url = uri("https://maven.pkg.jetbrains.space/public/p/compose/dev") }
}

dependencies {
    implementation("fr.epita.java:lang:1.0.0")
    implementation("ch.qos.logback:logback-classic:1.2.3")
    implementation("org.eclipse.jgit:org.eclipse.jgit:5.11.1.202105131744-r")
    implementation("org.apache.lucene:lucene-core:8.8.2")
    implementation("org.apache.lucene:lucene-queryparser:8.8.2")
    implementation("org.projectlombok:lombok:1.18.20")
    implementation("org.apache.commons:commons-compress:1.20")
    implementation("org.apache.maven:maven-compat:3.6.3")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.11.1")
    implementation("org.assertj:assertj-core:3.19.0")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.7.1")
    implementation(compose.desktop.currentOs)
    api(compose.materialIconsExtended)
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

group = "fr.epita.assistant"
version = "1.0.0-SNAPSHOT"
description = "ping-ref"
java.sourceCompatibility = JavaVersion.VERSION_16

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "utf-8"
}
