/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://gitlab.cri.epita.fr/api/v4/groups/3042/-/packages/maven/")
    }

    maven {
        url = uri("https://maven.pkg.github.com/TesseractFR/TesseractLib")
    }

    maven {
        url = uri("https://maven.pkg.github.com/BananaPuncher714/Cartographer2")
    }

    maven {
        url = uri("https://maven.pkg.github.com/TesseractFR/ElytraRace")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("fr.epita.java:lang:1.0.0")
    implementation("ch.qos.logback:logback-classic:1.2.3")
    implementation("org.eclipse.jgit:org.eclipse.jgit:5.11.1.202105131744-r")
    implementation("org.apache.lucene:lucene-core:8.8.2")
    implementation("org.apache.lucene:lucene-queryparser:8.8.2")
    implementation("org.projectlombok:lombok:1.18.20")
    implementation("org.apache.commons:commons-compress:1.20")
    implementation("org.apache.maven:maven-compat:3.6.3")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.11.1")
    implementation("org.assertj:assertj-core:3.19.0")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.7.1")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

group = "fr.epita.assistant"
version = "1.0.0-SNAPSHOT"
description = "ping-ref"
java.sourceCompatibility = JavaVersion.VERSION_16

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "utf-8"
}
